// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta    `orm:"table:user, do:true"`
	Id        interface{} // UID
	Name      interface{} // 账号
	Password  interface{} // MD5密码
	Nickename interface{} // 昵称
	Status    interface{} // 状态0:启用 1:禁用
}
